### ISSUE TITLE
How to install it

### ISSUE THREAD

**Issue by ricardomalagon** [heineiuo/react-native-draftjs#1]
Hi, can i set this library on my react native project? and if yes how can i do it?

**Comment by heineiuo** [comment]
@ricardomalagon I'm afraid this codebase is little outdated 😥. Maybe you can implement it yourself with architecture (simplified) below:

1. Create a web page based on `react`, `react-dom` and `draft-js` and put it on your server or github pages.
2. Use `react-native-webview` to load the webpage uri.
3. Send raw data(JSON format) to webpage by `.injectJavaScript` (RN side)
4. Receive message and convert to `draft-js` object (WEB side)
5. Implement a toolbar with buttons, each button inject a message to webpage (RN side)
6. Handle the message from button and change draft styles. (WEB side)
7. Provide a serialize method to convert `draft-js` object to JSON and send to RN (WEB side)
8. Call the serialize method and store the JSON if needed. (RN side)
